bgp:
-   bestpath:
        as_path:
            confed: false
            ignore: false
            multipath_relax: false
            multipath_relax_as_set: false
        compare_routerid: false
        med:
            always_compare_med: false
            confed: false
            missing_as_worst: false
    bgp_as: '4'
    graceful_restart:
        enabled: false
        preserve_fw_state: false
    log_neighbor_changes: false
    vrf_name: default
interfaces:
-   enabled: true
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet0
    speed: SPEED_25GB
-   enabled: true
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet1
    speed: SPEED_25GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet10
    speed: SPEED_25GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet11
    speed: SPEED_25GB
-   description: hi test
    enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet12
    speed: SPEED_25GB
-   description: hi ans
    enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet13
    speed: SPEED_25GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet14
    speed: SPEED_25GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet15
    speed: SPEED_25GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet16
    speed: SPEED_25GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet17
    speed: SPEED_25GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet18
    speed: SPEED_25GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet19
    speed: SPEED_25GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet2
    speed: SPEED_25GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet20
    speed: SPEED_25GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet21
    speed: SPEED_25GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet22
    speed: SPEED_25GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet23
    speed: SPEED_25GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet24
    speed: SPEED_25GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet25
    speed: SPEED_25GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet26
    speed: SPEED_25GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet27
    speed: SPEED_25GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet28
    speed: SPEED_25GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet29
    speed: SPEED_25GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet3
    speed: SPEED_25GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet30
    speed: SPEED_25GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet31
    speed: SPEED_25GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet32
    speed: SPEED_25GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet33
    speed: SPEED_25GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet34
    speed: SPEED_25GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet35
    speed: SPEED_25GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet36
    speed: SPEED_25GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet37
    speed: SPEED_25GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet38
    speed: SPEED_25GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet39
    speed: SPEED_25GB
-   description: hi
    enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet4
    speed: SPEED_25GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet40
    speed: SPEED_25GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet41
    speed: SPEED_25GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet42
    speed: SPEED_25GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet43
    speed: SPEED_25GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet44
    speed: SPEED_25GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet45
    speed: SPEED_25GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet46
    speed: SPEED_25GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet47
    speed: SPEED_25GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet48
    speed: SPEED_100GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet5
    speed: SPEED_25GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet52
    speed: SPEED_100GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet56
    speed: SPEED_100GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet6
    speed: SPEED_25GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet60
    speed: SPEED_100GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet64
    speed: SPEED_100GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet68
    speed: SPEED_100GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet7
    speed: SPEED_25GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet72
    speed: SPEED_100GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet76
    speed: SPEED_100GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet8
    speed: SPEED_25GB
-   enabled: false
    fec: FEC_DISABLED
    mtu: 9100
    name: Ethernet9
    speed: SPEED_25GB
-   description: hi loopback
    enabled: true
    name: Loopback100
-   enabled: true
    name: Loopback91
-   enabled: true
    mtu: 9100
    name: PortChannel12
-   description: Web-Servers
    enabled: true
    mtu: 9100
    name: Vlan100
-   enabled: true
    mtu: 9100
    name: Vlan11
-   enabled: true
    mtu: 9100
    name: Vlan12
-   enabled: true
    mtu: 9100
    name: Vlan13
-   description: DB-Servers
    enabled: true
    mtu: 9100
    name: Vlan200
l2_interfaces:
-   access:
        vlan: 12
    name: Ethernet12
-   access:
        vlan: 11
    name: Ethernet13
    trunk:
        allowed_vlans:
        -   vlan: '13'
        -   vlan: '12'
-   access:
        vlan: 100
    name: Ethernet3
-   access:
        vlan: 100
    name: Ethernet25
-   access:
        vlan: 100
    name: Ethernet26
l3_interfaces:
-   ipv4:
        addresses:
        -   address: 192.168.101.1/30
            secondary: false
    ipv6:
        enabled: false
    name: Ethernet0
-   ipv4:
        addresses:
        -   address: 192.168.100.101/24
            secondary: false
    ipv6:
        enabled: false
    name: Ethernet1
-   ipv6:
        enabled: true
    name: Ethernet24
-   ipv4:
        addresses:
        -   address: 101.1.1.1/32
            secondary: false
    ipv6:
        enabled: false
    name: Loopback100
-   ipv6:
        addresses:
        -   address: 150::1/16
        enabled: false
    name: Vlan11
lag_interfaces:
-   mode: lacp
    name: PortChannel12
vlans:
-   autostate: false
    vlan_id: 11
-   autostate: false
    vlan_id: 12
-   vlan_id: 13
-   autostate: false
    description: Web-Servers
    vlan_id: 100
-   description: App-Servers
    vlan_id: 101
-   description: DB-Servers
    vlan_id: 200
-   description: App-Servers2
    vlan_id: 301
